# Generated by Django 6.0.4 on 2026-05-08 06:25

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import strategis.utils.uploads
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActorType',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('name_fr', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_fr', models.TextField(blank=True, null=True, verbose_name='description')),
                ('requires_validation', models.BooleanField(default=True, verbose_name='requires validation')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('required_documents', models.JSONField(default=list, help_text='List of required documents, e.g. [{"label": "...", "required": true, "accepted_formats": ["pdf", "jpg"]}]', verbose_name='required documents')),
            ],
            options={
                'verbose_name': 'actor type',
                'verbose_name_plural': 'actor types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('rejected', 'Rejected'), ('revoked', 'Revoked'), ('awaiting_documents', 'Awaiting Documents')], default='pending', max_length=20, verbose_name='status')),
                ('is_available', models.BooleanField(default=True, verbose_name='available')),
                ('operation_radius_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='operation radius (km)')),
                ('max_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='max quantity')),
                ('max_quantity_unit', models.CharField(blank=True, max_length=20, verbose_name='max quantity unit')),
                ('processing_delay', models.CharField(blank=True, choices=[('immediate', 'Immediate'), ('within_48h', 'Within 48h'), ('within_7_days', 'Within 7 Days'), ('over_7_days', 'Over 7 Days'), ('uncertain', 'Uncertain')], max_length=20, verbose_name='processing delay')),
                ('reliability_level', models.CharField(blank=True, choices=[('certified', 'Certified'), ('validated_good_history', 'Validated - Good History'), ('validated', 'Validated'), ('declared', 'Declared'), ('not_validated', 'Not Validated')], max_length=25, verbose_name='reliability level')),
                ('compliance_level', models.CharField(blank=True, choices=[('approved', 'Approved'), ('validated', 'Validated'), ('compliant', 'Compliant'), ('at_risk', 'At Risk'), ('non_compliant', 'Non-Compliant')], max_length=20, verbose_name='compliance level')),
                ('approved_for_category_c', models.BooleanField(default=False, verbose_name='approved for category C')),
                ('variants', models.JSONField(default=list, verbose_name='variants')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='validated at')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='rejection reason')),
                ('revocation_reason', models.TextField(blank=True, verbose_name='revocation reason')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_actors', to=settings.AUTH_USER_MODEL, verbose_name='validated by')),
                ('actor_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actors', to='profiles.actortype', verbose_name='actor type')),
            ],
            options={
                'verbose_name': 'actor',
                'verbose_name_plural': 'actors',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ActorDocument',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255, verbose_name='label')),
                ('file', models.FileField(upload_to=strategis.utils.uploads.upload_to, verbose_name='file')),
                ('is_required', models.BooleanField(default=True, verbose_name='required')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded at')),
                ('admin_note', models.TextField(blank=True, verbose_name='admin note')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='profiles.actor', verbose_name='actor')),
            ],
            options={
                'verbose_name': 'actor document',
                'verbose_name_plural': 'actor documents',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalProfile',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255, verbose_name='company name')),
                ('entity_type', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company'), ('ngo', 'NGO'), ('public_institution', 'Public Institution'), ('other', 'Other')], max_length=20, verbose_name='entity type')),
                ('company_registration_number', models.CharField(blank=True, max_length=100, verbose_name='company registration number')),
                ('tax_id_number', models.CharField(max_length=100, verbose_name='tax ID number')),
                ('phone', models.CharField(max_length=30, verbose_name='phone')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('intervention_zone', models.CharField(blank=True, max_length=255, verbose_name='intervention zone')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Geographic position (longitude, latitude) in WGS84', null=True, srid=4326, verbose_name='location')),
                ('tier', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='free', max_length=10, verbose_name='tier')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'professional profile',
                'verbose_name_plural': 'professional profiles',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='PremiumUpgradeRequest',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('activated', 'Activated'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20, verbose_name='status')),
                ('plan', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='', max_length=10, verbose_name='plan')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='activated at')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='rejected at')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='rejection reason')),
                ('admin_note', models.TextField(blank=True, verbose_name='admin note')),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_premium_requests', to=settings.AUTH_USER_MODEL, verbose_name='activated by')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_requests', to='profiles.professionalprofile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'premium upgrade request',
                'verbose_name_plural': 'premium upgrade requests',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='actor',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actors', to='profiles.professionalprofile', verbose_name='profile'),
        ),
    ]
