export interface Country {
  iso: string;
  dialCode: string;
  name: string;
}

function flag(iso: string): string {
  const normalizedIso = iso.toUpperCase();

  if (!/^[A-Z]{2}$/.test(normalizedIso)) {
    return '';
  }

  return [...normalizedIso]
    .map((c) => String.fromCodePoint(0x1f1e6 + c.charCodeAt(0) - 65))
    .join('');
}

export const COUNTRIES: Country[] = [
  { iso: 'AF', dialCode: '+93', name: 'Afghanistan' },
  { iso: 'AL', dialCode: '+355', name: 'Albania' },
  { iso: 'DZ', dialCode: '+213', name: 'Algeria' },
  { iso: 'AD', dialCode: '+376', name: 'Andorra' },
  { iso: 'AO', dialCode: '+244', name: 'Angola' },
  { iso: 'AG', dialCode: '+1268', name: 'Antigua & Barbuda' },
  { iso: 'AR', dialCode: '+54', name: 'Argentina' },
  { iso: 'AM', dialCode: '+374', name: 'Armenia' },
  { iso: 'AU', dialCode: '+61', name: 'Australia' },
  { iso: 'AT', dialCode: '+43', name: 'Austria' },
  { iso: 'AZ', dialCode: '+994', name: 'Azerbaijan' },
  { iso: 'BS', dialCode: '+1242', name: 'Bahamas' },
  { iso: 'BH', dialCode: '+973', name: 'Bahrain' },
  { iso: 'BD', dialCode: '+880', name: 'Bangladesh' },
  { iso: 'BB', dialCode: '+1246', name: 'Barbados' },
  { iso: 'BY', dialCode: '+375', name: 'Belarus' },
  { iso: 'BE', dialCode: '+32', name: 'Belgium' },
  { iso: 'BZ', dialCode: '+501', name: 'Belize' },
  { iso: 'BJ', dialCode: '+229', name: 'Benin' },
  { iso: 'BT', dialCode: '+975', name: 'Bhutan' },
  { iso: 'BO', dialCode: '+591', name: 'Bolivia' },
  { iso: 'BA', dialCode: '+387', name: 'Bosnia & Herzegovina' },
  { iso: 'BW', dialCode: '+267', name: 'Botswana' },
  { iso: 'BR', dialCode: '+55', name: 'Brazil' },
  { iso: 'BN', dialCode: '+673', name: 'Brunei' },
  { iso: 'BG', dialCode: '+359', name: 'Bulgaria' },
  { iso: 'BF', dialCode: '+226', name: 'Burkina Faso' },
  { iso: 'BI', dialCode: '+257', name: 'Burundi' },
  { iso: 'CV', dialCode: '+238', name: 'Cabo Verde' },
  { iso: 'KH', dialCode: '+855', name: 'Cambodia' },
  { iso: 'CM', dialCode: '+237', name: 'Cameroon' },
  { iso: 'CA', dialCode: '+1', name: 'Canada' },
  { iso: 'CF', dialCode: '+236', name: 'Central African Republic' },
  { iso: 'TD', dialCode: '+235', name: 'Chad' },
  { iso: 'CL', dialCode: '+56', name: 'Chile' },
  { iso: 'CN', dialCode: '+86', name: 'China' },
  { iso: 'CO', dialCode: '+57', name: 'Colombia' },
  { iso: 'KM', dialCode: '+269', name: 'Comoros' },
  { iso: 'CG', dialCode: '+242', name: 'Congo' },
  { iso: 'CD', dialCode: '+243', name: 'Congo (DRC)' },
  { iso: 'CR', dialCode: '+506', name: 'Costa Rica' },
  { iso: 'CI', dialCode: '+225', name: "Côte d'Ivoire" },
  { iso: 'HR', dialCode: '+385', name: 'Croatia' },
  { iso: 'CU', dialCode: '+53', name: 'Cuba' },
  { iso: 'CY', dialCode: '+357', name: 'Cyprus' },
  { iso: 'CZ', dialCode: '+420', name: 'Czech Republic' },
  { iso: 'DK', dialCode: '+45', name: 'Denmark' },
  { iso: 'DJ', dialCode: '+253', name: 'Djibouti' },
  { iso: 'DM', dialCode: '+1767', name: 'Dominica' },
  { iso: 'DO', dialCode: '+1809', name: 'Dominican Republic' },
  { iso: 'EC', dialCode: '+593', name: 'Ecuador' },
  { iso: 'EG', dialCode: '+20', name: 'Egypt' },
  { iso: 'SV', dialCode: '+503', name: 'El Salvador' },
  { iso: 'GQ', dialCode: '+240', name: 'Equatorial Guinea' },
  { iso: 'ER', dialCode: '+291', name: 'Eritrea' },
  { iso: 'EE', dialCode: '+372', name: 'Estonia' },
  { iso: 'SZ', dialCode: '+268', name: 'Eswatini' },
  { iso: 'ET', dialCode: '+251', name: 'Ethiopia' },
  { iso: 'FJ', dialCode: '+679', name: 'Fiji' },
  { iso: 'FI', dialCode: '+358', name: 'Finland' },
  { iso: 'FR', dialCode: '+33', name: 'France' },
  { iso: 'GA', dialCode: '+241', name: 'Gabon' },
  { iso: 'GM', dialCode: '+220', name: 'Gambia' },
  { iso: 'GE', dialCode: '+995', name: 'Georgia' },
  { iso: 'DE', dialCode: '+49', name: 'Germany' },
  { iso: 'GH', dialCode: '+233', name: 'Ghana' },
  { iso: 'GR', dialCode: '+30', name: 'Greece' },
  { iso: 'GD', dialCode: '+1473', name: 'Grenada' },
  { iso: 'GT', dialCode: '+502', name: 'Guatemala' },
  { iso: 'GN', dialCode: '+224', name: 'Guinea' },
  { iso: 'GW', dialCode: '+245', name: 'Guinea-Bissau' },
  { iso: 'GY', dialCode: '+592', name: 'Guyana' },
  { iso: 'HT', dialCode: '+509', name: 'Haiti' },
  { iso: 'HN', dialCode: '+504', name: 'Honduras' },
  { iso: 'HU', dialCode: '+36', name: 'Hungary' },
  { iso: 'IS', dialCode: '+354', name: 'Iceland' },
  { iso: 'IN', dialCode: '+91', name: 'India' },
  { iso: 'ID', dialCode: '+62', name: 'Indonesia' },
  { iso: 'IR', dialCode: '+98', name: 'Iran' },
  { iso: 'IQ', dialCode: '+964', name: 'Iraq' },
  { iso: 'IE', dialCode: '+353', name: 'Ireland' },
  { iso: 'IL', dialCode: '+972', name: 'Israel' },
  { iso: 'IT', dialCode: '+39', name: 'Italy' },
  { iso: 'JM', dialCode: '+1876', name: 'Jamaica' },
  { iso: 'JP', dialCode: '+81', name: 'Japan' },
  { iso: 'JO', dialCode: '+962', name: 'Jordan' },
  { iso: 'KZ', dialCode: '+7', name: 'Kazakhstan' },
  { iso: 'KE', dialCode: '+254', name: 'Kenya' },
  { iso: 'KI', dialCode: '+686', name: 'Kiribati' },
  { iso: 'KW', dialCode: '+965', name: 'Kuwait' },
  { iso: 'KG', dialCode: '+996', name: 'Kyrgyzstan' },
  { iso: 'LA', dialCode: '+856', name: 'Laos' },
  { iso: 'LV', dialCode: '+371', name: 'Latvia' },
  { iso: 'LB', dialCode: '+961', name: 'Lebanon' },
  { iso: 'LS', dialCode: '+266', name: 'Lesotho' },
  { iso: 'LR', dialCode: '+231', name: 'Liberia' },
  { iso: 'LY', dialCode: '+218', name: 'Libya' },
  { iso: 'LI', dialCode: '+423', name: 'Liechtenstein' },
  { iso: 'LT', dialCode: '+370', name: 'Lithuania' },
  { iso: 'LU', dialCode: '+352', name: 'Luxembourg' },
  { iso: 'MG', dialCode: '+261', name: 'Madagascar' },
  { iso: 'MW', dialCode: '+265', name: 'Malawi' },
  { iso: 'MY', dialCode: '+60', name: 'Malaysia' },
  { iso: 'MV', dialCode: '+960', name: 'Maldives' },
  { iso: 'ML', dialCode: '+223', name: 'Mali' },
  { iso: 'MT', dialCode: '+356', name: 'Malta' },
  { iso: 'MH', dialCode: '+692', name: 'Marshall Islands' },
  { iso: 'MR', dialCode: '+222', name: 'Mauritania' },
  { iso: 'MU', dialCode: '+230', name: 'Mauritius' },
  { iso: 'MX', dialCode: '+52', name: 'Mexico' },
  { iso: 'FM', dialCode: '+691', name: 'Micronesia' },
  { iso: 'MD', dialCode: '+373', name: 'Moldova' },
  { iso: 'MC', dialCode: '+377', name: 'Monaco' },
  { iso: 'MN', dialCode: '+976', name: 'Mongolia' },
  { iso: 'ME', dialCode: '+382', name: 'Montenegro' },
  { iso: 'MA', dialCode: '+212', name: 'Morocco' },
  { iso: 'MZ', dialCode: '+258', name: 'Mozambique' },
  { iso: 'MM', dialCode: '+95', name: 'Myanmar' },
  { iso: 'NA', dialCode: '+264', name: 'Namibia' },
  { iso: 'NR', dialCode: '+674', name: 'Nauru' },
  { iso: 'NP', dialCode: '+977', name: 'Nepal' },
  { iso: 'NL', dialCode: '+31', name: 'Netherlands' },
  { iso: 'NZ', dialCode: '+64', name: 'New Zealand' },
  { iso: 'NI', dialCode: '+505', name: 'Nicaragua' },
  { iso: 'NE', dialCode: '+227', name: 'Niger' },
  { iso: 'NG', dialCode: '+234', name: 'Nigeria' },
  { iso: 'NO', dialCode: '+47', name: 'Norway' },
  { iso: 'OM', dialCode: '+968', name: 'Oman' },
  { iso: 'PK', dialCode: '+92', name: 'Pakistan' },
  { iso: 'PW', dialCode: '+680', name: 'Palau' },
  { iso: 'PA', dialCode: '+507', name: 'Panama' },
  { iso: 'PG', dialCode: '+675', name: 'Papua New Guinea' },
  { iso: 'PY', dialCode: '+595', name: 'Paraguay' },
  { iso: 'PE', dialCode: '+51', name: 'Peru' },
  { iso: 'PH', dialCode: '+63', name: 'Philippines' },
  { iso: 'PL', dialCode: '+48', name: 'Poland' },
  { iso: 'PT', dialCode: '+351', name: 'Portugal' },
  { iso: 'QA', dialCode: '+974', name: 'Qatar' },
  { iso: 'RO', dialCode: '+40', name: 'Romania' },
  { iso: 'RU', dialCode: '+7', name: 'Russia' },
  { iso: 'RW', dialCode: '+250', name: 'Rwanda' },
  { iso: 'KN', dialCode: '+1869', name: 'Saint Kitts & Nevis' },
  { iso: 'LC', dialCode: '+1758', name: 'Saint Lucia' },
  { iso: 'VC', dialCode: '+1784', name: 'Saint Vincent & the Grenadines' },
  { iso: 'WS', dialCode: '+685', name: 'Samoa' },
  { iso: 'SM', dialCode: '+378', name: 'San Marino' },
  { iso: 'ST', dialCode: '+239', name: 'São Tomé & Príncipe' },
  { iso: 'SA', dialCode: '+966', name: 'Saudi Arabia' },
  { iso: 'SN', dialCode: '+221', name: 'Senegal' },
  { iso: 'RS', dialCode: '+381', name: 'Serbia' },
  { iso: 'SC', dialCode: '+248', name: 'Seychelles' },
  { iso: 'SL', dialCode: '+232', name: 'Sierra Leone' },
  { iso: 'SG', dialCode: '+65', name: 'Singapore' },
  { iso: 'SK', dialCode: '+421', name: 'Slovakia' },
  { iso: 'SI', dialCode: '+386', name: 'Slovenia' },
  { iso: 'SB', dialCode: '+677', name: 'Solomon Islands' },
  { iso: 'SO', dialCode: '+252', name: 'Somalia' },
  { iso: 'ZA', dialCode: '+27', name: 'South Africa' },
  { iso: 'SS', dialCode: '+211', name: 'South Sudan' },
  { iso: 'ES', dialCode: '+34', name: 'Spain' },
  { iso: 'LK', dialCode: '+94', name: 'Sri Lanka' },
  { iso: 'SD', dialCode: '+249', name: 'Sudan' },
  { iso: 'SR', dialCode: '+597', name: 'Suriname' },
  { iso: 'SE', dialCode: '+46', name: 'Sweden' },
  { iso: 'CH', dialCode: '+41', name: 'Switzerland' },
  { iso: 'SY', dialCode: '+963', name: 'Syria' },
  { iso: 'TW', dialCode: '+886', name: 'Taiwan' },
  { iso: 'TJ', dialCode: '+992', name: 'Tajikistan' },
  { iso: 'TZ', dialCode: '+255', name: 'Tanzania' },
  { iso: 'TH', dialCode: '+66', name: 'Thailand' },
  { iso: 'TL', dialCode: '+670', name: 'Timor-Leste' },
  { iso: 'TG', dialCode: '+228', name: 'Togo' },
  { iso: 'TO', dialCode: '+676', name: 'Tonga' },
  { iso: 'TT', dialCode: '+1868', name: 'Trinidad & Tobago' },
  { iso: 'TN', dialCode: '+216', name: 'Tunisia' },
  { iso: 'TR', dialCode: '+90', name: 'Turkey' },
  { iso: 'TM', dialCode: '+993', name: 'Turkmenistan' },
  { iso: 'TV', dialCode: '+688', name: 'Tuvalu' },
  { iso: 'UG', dialCode: '+256', name: 'Uganda' },
  { iso: 'UA', dialCode: '+380', name: 'Ukraine' },
  { iso: 'AE', dialCode: '+971', name: 'United Arab Emirates' },
  { iso: 'GB', dialCode: '+44', name: 'United Kingdom' },
  { iso: 'US', dialCode: '+1', name: 'United States' },
  { iso: 'UY', dialCode: '+598', name: 'Uruguay' },
  { iso: 'UZ', dialCode: '+998', name: 'Uzbekistan' },
  { iso: 'VU', dialCode: '+678', name: 'Vanuatu' },
  { iso: 'VE', dialCode: '+58', name: 'Venezuela' },
  { iso: 'VN', dialCode: '+84', name: 'Vietnam' },
  { iso: 'YE', dialCode: '+967', name: 'Yemen' },
  { iso: 'ZM', dialCode: '+260', name: 'Zambia' },
  { iso: 'ZW', dialCode: '+263', name: 'Zimbabwe' },
];

export function getFlag(iso: string): string {
  return flag(iso);
}

export function findCountryByDialCode(e164: string): Country | undefined {
  const sorted = [...COUNTRIES].sort(
    (a, b) => b.dialCode.length - a.dialCode.length,
  );
  return sorted.find((c) => e164.startsWith(c.dialCode));
}
