services:
  django: &django
    image: ghcr.io/valerymelou/strategis-api/django:${TAG}
    pull_policy: always
    expose:
      - 5000
    env_file:
      - ./.envs/.production/.django
    command: /start
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  celeryworker:
    <<: *django
    image: ghcr.io/valerymelou/strategis-api/django:${TAG}
    pull_policy: always
    command: /start-celeryworker
    healthcheck:
      test: [
          "CMD-SHELL",
          "/entrypoint celery -A config.celery_app inspect ping -d
          celery@$(hostname)",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  celerybeat:
    <<: *django
    image: ghcr.io/valerymelou/strategis-api/django:${TAG}
    pull_policy: always
    command: /start-celerybeat
    healthcheck:
      test: ["CMD-SHELL", "/entrypoint celery -A config.celery_app --version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  flower:
    <<: *django
    image: ghcr.io/valerymelou/strategis-api/django:${TAG}
    pull_policy: always
    expose:
      - 5555
    command: /start-flower
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'curl -f --user "$CELERY_FLOWER_USER:$CELERY_FLOWER_PASSWORD" http://localhost:5555/',
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
