# Generated by Django 6.0.4 on 2026-05-19 14:09

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_seed_actor_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CEDCode',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='code')),
                ('chapter_code', models.CharField(max_length=10, verbose_name='chapter code')),
                ('sub_category_code', models.CharField(max_length=20, verbose_name='sub-category code')),
                ('sub_category_label', models.TextField(verbose_name='sub-category label')),
                ('label', models.TextField(verbose_name='label')),
                ('is_hazardous', models.BooleanField(default=False, verbose_name='hazardous')),
                ('category', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1, verbose_name='category')),
                ('sub_category_a', models.CharField(blank=True, max_length=50, verbose_name='sub-category A')),
                ('sub_category_a_label', models.CharField(blank=True, max_length=255, verbose_name='sub-category A label')),
                ('allowed_units', models.JSONField(default=list, verbose_name='allowed units')),
                ('points_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='points per unit')),
                ('reference_scenario', models.CharField(blank=True, max_length=20, verbose_name='reference scenario')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'CED code',
                'verbose_name_plural': 'CED codes',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['category'], name='waste_cedco_categor_d52d97_idx'), models.Index(fields=['sub_category_a'], name='waste_cedco_sub_cat_b29854_idx')],
            },
        ),
        migrations.CreateModel(
            name='WasteLot',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(verbose_name='description')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='quantity')),
                ('unit', models.CharField(max_length=20, verbose_name='unit')),
                ('address', models.TextField(verbose_name='address')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('availability_date', models.DateField(verbose_name='availability date')),
                ('additional_info', models.TextField(blank=True, verbose_name='additional info')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_validation', 'Under Validation'), ('correction_required', 'Correction Required'), ('validated', 'Validated'), ('categorized', 'Categorized'), ('routes_identified', 'Routes Identified'), ('no_route_available', 'No Route Available'), ('categorization_error', 'Categorization Error')], default='submitted', max_length=25, verbose_name='status')),
                ('admin_correction_note', models.TextField(blank=True, verbose_name='admin correction note')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='rejection reason')),
                ('ced_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waste_lots', to='waste.cedcode', verbose_name='CED code')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waste_lots', to='profiles.actor', verbose_name='producer')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_lots', to=settings.AUTH_USER_MODEL, verbose_name='reviewed by')),
            ],
            options={
                'verbose_name': 'waste lot',
                'verbose_name_plural': 'waste lots',
            },
        ),
        migrations.CreateModel(
            name='LotCategorization',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1, verbose_name='category')),
                ('sub_category_a', models.CharField(blank=True, max_length=50, verbose_name='sub-category A')),
                ('potential_points', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='potential points')),
                ('categorized_at', models.DateTimeField(auto_now_add=True, verbose_name='categorized at')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('lot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='categorization', to='waste.wastelot', verbose_name='lot')),
            ],
            options={
                'verbose_name': 'lot categorization',
                'verbose_name_plural': 'lot categorizations',
            },
        ),
        migrations.CreateModel(
            name='WasteLotPhoto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.ImageField(upload_to='lot_photos/%Y/%m/', verbose_name='file')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded at')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='waste.wastelot', verbose_name='lot')),
            ],
            options={
                'verbose_name': 'waste lot photo',
                'verbose_name_plural': 'waste lot photos',
            },
        ),
        migrations.AddIndex(
            model_name='wastelot',
            index=models.Index(fields=['status'], name='waste_waste_status_03dd70_idx'),
        ),
        migrations.AddIndex(
            model_name='wastelot',
            index=models.Index(fields=['producer_id'], name='waste_waste_produce_84c8f0_idx'),
        ),
    ]
