# Generated by Django 6.0.4 on 2026-05-20 09:47

import strategis.utils.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0002_seed_ced_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastelotphoto',
            name='file',
            field=models.ImageField(upload_to=strategis.utils.uploads.upload_to, verbose_name='file'),
        ),
    ]
