name: Build and Push API Docker Image

on:
  workflow_run:
    workflows: ["CI API"]
    branches: ["master"]
    types:
      - completed

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: ${{ github.event.workflow_run.head_branch == 'master' &&
      'production' || 'staging' }}
    env:
      DEPLOY_ENV: ${{ github.event.workflow_run.head_branch == 'master' &&
        'production' || 'staging' }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Set environment suffix
        id: suffix
        run: |
          if [[ "${{ github.event.workflow_run.head_branch }}" == "master" ]]; then
            echo "env=production" >> $GITHUB_OUTPUT
          else
            echo "env=staging" >> $GITHUB_OUTPUT
          fi

      - name: Log in to the Container registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # This handles lowercasing the repo name automatically
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=staging
            type=raw,value=production
            type=sha

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push Django
        uses: docker/build-push-action@v7
        with:
          context: ./apps/strategis-api
          file: ./apps/strategis-api/compose/production/django/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-api/django:${{
            steps.suffix.outputs.env }}
